import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header/index'
import SideBar from '../components/sidebar/index'

export default function Home() {
  return (
    <div className='bg-gray-100 h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        <Header/>
        <div>
          <SideBar/>
        </div>
      </main>
    </div>
  )
}
